'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class VTSEntitiesFailRateByDefectcode
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=VTSEntitiesFailRateByDefectcode")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function RptFailRateByDefectCode(fromDate As String, todate As String, stationName As String, defect As String, visit As String, vehicleType As String, vehicleCategory As Nullable(Of Integer)) As ObjectResult(Of RptFailRateByDefectCode_Result)
        Dim fromDateParameter As ObjectParameter = If(fromDate IsNot Nothing, New ObjectParameter("FromDate", fromDate), New ObjectParameter("FromDate", GetType(String)))

        Dim todateParameter As ObjectParameter = If(todate IsNot Nothing, New ObjectParameter("Todate", todate), New ObjectParameter("Todate", GetType(String)))

        Dim stationNameParameter As ObjectParameter = If(stationName IsNot Nothing, New ObjectParameter("StationName", stationName), New ObjectParameter("StationName", GetType(String)))

        Dim defectParameter As ObjectParameter = If(defect IsNot Nothing, New ObjectParameter("Defect", defect), New ObjectParameter("Defect", GetType(String)))

        Dim visitParameter As ObjectParameter = If(visit IsNot Nothing, New ObjectParameter("Visit", visit), New ObjectParameter("Visit", GetType(String)))

        Dim vehicleTypeParameter As ObjectParameter = If(vehicleType IsNot Nothing, New ObjectParameter("VehicleType", vehicleType), New ObjectParameter("VehicleType", GetType(String)))

        Dim vehicleCategoryParameter As ObjectParameter = If(vehicleCategory.HasValue, New ObjectParameter("VehicleCategory", vehicleCategory), New ObjectParameter("VehicleCategory", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of RptFailRateByDefectCode_Result)("RptFailRateByDefectCode", fromDateParameter, todateParameter, stationNameParameter, defectParameter, visitParameter, vehicleTypeParameter, vehicleCategoryParameter)
    End Function

End Class
